// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DDona.Kiper.Domain
{
    public partial class Condominio
    {
        public Condominio()
        {
            Apartamento = new HashSet<Apartamento>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<Apartamento> Apartamento { get; set; }
    }
}