// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DDona.Kiper.Domain
{
    public partial class Morador
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Cpf { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
        public int? ApartamentoId { get; set; }

        public virtual Apartamento Apartamento { get; set; }
    }
}